### ISSUE TITLE
Nastavit prismu a postgres

### ISSUE THREAD

**Issue by tomaskebrle** [madebyqwerty/database-service#12]
```[tasklist]
### Tasks
- [x] Nastavit Deno
- [x] Nastavit express v Deno
- [x] Nastavit prismu
- [x] Nastavit postgres
- [x] Nastavit swagger
- [ ] https://github.com/madebyqwerty/database-service/issues/13
- [ ] https://github.com/madebyqwerty/database-service/issues/9
```
