### ISSUE TITLE
Vytvořit testy pro uživatelský endpointy

### ISSUE THREAD

**Issue by tomaskebrle** [madebyqwerty/database-service#17]
```[tasklist]
### Tasks
- [x] Otestovat získání uživatelů
- [x] Otestovat vytvoření uživatelů
- [ ] https://github.com/madebyqwerty/database-service/issues/14
```
