### ISSUE TITLE
Vytvořit endpointy pro absence

### ISSUE THREAD

**Issue by tomaskebrle** [madebyqwerty/database-service#23]
```[tasklist]
### Tasks
- [ ] https://github.com/madebyqwerty/database-service/issues/8
- [ ] https://github.com/madebyqwerty/database-service/issues/11
- [ ] https://github.com/madebyqwerty/database-service/issues/24
```
